### ISSUE TITLE
Bug in HigherOrderNetwork.reduceToGCC

### ISSUE THREAD

**Issue by yanrabbit** [IngoScholtes/pathpy#1]
I used getgcc to extract the strongly connected component of a second-order network. 

It returned an error, and said that dictionary changed size during interaction 
del self.edges[(u,v)]

**Comment by IngoScholtes** [comment]
I just reproduced this bug. Stay tuned for a fix.

**Comment by IngoScholtes** [comment]
Fixed in [d1830bf](https://github.com/IngoScholtes/pathpy/commit/d1830bf2bd281a88e466e554544f0fff796cc599)
