### ISSUE TITLE
python2 compatibility

### ISSUE THREAD

**Issue by carissableker** [IngoScholtes/pathpy#15]
Nowhere in the documentation does it mention that this module is not python2 compatible, however:

    import igraph
    import numpy as np
    import pathpy as pp

Results in the error: 

  File "/home/user99/miniconda2/lib/python2.7/site-packages/pathpy/HigherOrderNetwork.py", line 728
    nonlocal index
                 ^
SyntaxError: invalid syntax

It would be great if it was python2 compatible, but otherwise could you specify in the docs that it is not?

**Comment by IngoScholtes** [comment]
Thanks for noticing. 

Indeed, python 2.x compatibility was broken recently due to the inclusion of nonlocals. We'll check how to fix this in the next release. In general, it should be possible to make pathpy backwards compatible.
