### ISSUE TITLE
Misleading "to_undirected" method in Network class

### ISSUE THREAD

**Issue by VincenzoPerri** [IngoScholtes/pathpy#22]
The "to_undirected" method of the networks class loses the edge weights.  
It would be better to provide a method that allows preserving weights and removes only the directedness. The user should be able to choose how this is performed (sum, average...)

**Comment by verginer** [comment]
Hi Vincezo, could you open the issue on the development branch? :)

https://github.com/uzhdag/pathpy

And yes you are right the signature suggests that only the directionality is altered and not the properties.
