### ISSUE TITLE
Is this repo open source? No OSS License is specified.

### ISSUE THREAD

**Issue by verginer** [IngoScholtes/pathpy#3]
Sorry to bring this up,

but I have noticed that this repo does not have a `LICENSE` file specifying how it may be used.
I don't intend on infringing on any intellectual property, but I would like to fiddle around with the code and maybe share it as well here on github, however as per the GitHub Terms of Service,
if no Open Source Licensing is explicitly stated,  
>  the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.
https://help.github.com/articles/licensing-a-repository/

Maybe you would consider adding such as license?

see also: https://choosealicense.com/no-license/

**Comment by IngoScholtes** [comment]
Hi 

we are working on the license issue. However I need to check with the corresponding department here at ETH what license is acceptable for them. Please stay tuned.

**Comment by IngoScholtes** [comment]
Hi Luca 

we now clarified this internally and we licensed the project under the AGPL. We also corrected the license in the setup.py.

**Comment by verginer** [comment]
Thanks for the update! 👍
