### ISSUE TITLE
Test suit and Trevis CI integration

### ISSUE THREAD

**Issue by verginer** [IngoScholtes/pathpy#7]
Hi @IngoScholtes 

I have looked through the code since I find this project really nice and (also the paper),
and in the process of understanding it I have created a test suit covering 75% of `pathpy`s codebase, which highlights a few bugs I have found, and several `Errors` which I could not fix
(e.g. in the code the package or object `Distances` and `Utilities` are referenced but never declared see for example `GetTemporalBetweenness`, `GetTemporalBetweennessInstantaneous`)

For my fork I have also set up a travis ci integration to test the code against several python versions.
Which does also highlight several version related "bugs" or unexpected behavior.

I didn't want to create a pull request with such a large change not knowing if it is appreciated.
So my question is whether you would like to incorporate the test suit, and if so how you would
like me submit the changes.

Luca

**Comment by IngoScholtes** [comment]
Hi @verginer 

That's amazing, a more formal testing approach would be great. So I'll have a look and I'll let you know how we can proceed.

Best 

Ingo
